trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
 - template: build/default.yml
   parameters:
     # There aren't features in intiface-cli, so skip these steps
     check_all_features: false
     check_no_features: false
     # Build on all platforms
     cross: true
     # Skip minimum rust versions, only build on latest
     minrust: false

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/master
      endpoint: qdot
