[package]
name = "intiface-cli"
version = "23.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Command Line Interface frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-cli-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"
exclude = [".vscode/**"]

[dependencies]
# buttplug = { path = "../buttplug-rs/buttplug", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
buttplug = { version = "2.0.0", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
argh = "0.1.4"
async-std = { version = "1.8.0", features = ["attributes"] }
rcgen = "0.8.9"
log = "0.4.11"
futures = "0.3.8"
prost = "0.6.1"
async-channel = "1.5.1"
tracing-fmt = "0.1.1"
tracing-subscriber = "0.2.15"
tracing = "0.1.22"
tokio = { version = "1.0.1", features = ["sync"] }
log-panics = { version = "2.0.0", features = ["with-backtrace"] }

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.9"

[build-dependencies]
prost-build = "0.6.1"
vergen = "3.1.0"
