[package]
name = "intiface-cli"
version = "2.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Command Line Interface frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-cli-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"

[dependencies]
#buttplug = { path = "../buttplug-rs/buttplug", features = [ "btleplug-manager", "client-ws", "xinput" ] }
buttplug = { version = "0.2.2" }
argh = "0.1.3"
ws = "0.9.1"
async-std = { version = "1.5.0", features = ["unstable"] }
env_logger = "0.7.1"
# This needs to match the version of openssl in ws, so we can make
# sure we're compiling the correct thing. Using VSPKGRS_DYNAMIC here
# would require us to also redistribute the openssl DLL.
openssl = { version = "^0.10", features = ["vendored"]}
