[package]
name = "intiface-cli"
version = "50.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Command Line Interface frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-cli-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"
exclude = [".vscode/**"]

[dependencies]
# buttplug = { path = "../buttplug-rs/buttplug" }
buttplug = "5.1.9"
argh = "0.1.7"
log = "0.4.16"
futures = "0.3.21"
prost = "0.10.1"
async-channel = "1.6.1"
tracing-fmt = "0.1.1"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tracing = "0.1.34"
tokio = { version = "1.17.0", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util"] }
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
backtrace = "0.3.65"
ctrlc = "3.2.2"
tokio-util = "0.7.1"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.9"

[build-dependencies]
prost-build = "0.10.1"
vergen = "7.0.0"
