[package]
name = "intiface-cli"
version = "38.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Command Line Interface frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-cli-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"
exclude = [".vscode/**"]

[dependencies]
# buttplug = { path = "../buttplug-rs/buttplug" }
buttplug = "4.0.3"
argh = "0.1.4"
log = "0.4.14"
futures = "0.3.15"
prost = "0.7.0"
async-channel = "1.6.1"
tracing-fmt = "0.1.1"
tracing-subscriber = "0.2.18"
tracing = "0.1.26"
tokio = { version = "1.6.1", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util"] }
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
backtrace = "0.3.59"
ctrlc = "3.1.9"
tokio-util = "0.6.7"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.9"

[build-dependencies]
prost-build = "0.7.0"
vergen = "^3"
