[package]
name = "intiface-engine"
version = "1.4.2"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "CLI and Library frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-engine.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2021"
exclude = [".vscode/**"]

[lib]
name = "intiface_engine"
path = "src/lib.rs"

[[bin]]
name = "intiface-engine"
path = "src/bin/main.rs"

[features]
default=["crash_reporting"]
# crash_reporting=["sentry", "sentry-tracing"]
# Make crash reporting a null feature for now.
crash_reporting=[]
tokio_console=["console-subscriber"]

[dependencies]
# buttplug = { path = "../buttplug/buttplug" }
buttplug = { version = "7.1.5" }
argh = "0.1.12"
log = "0.4.20"
futures = "0.3.28"
tracing-fmt = "0.1.1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing = "0.1.37"
tokio = { version = "1.32.0", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
backtrace = "0.3.69"
ctrlc = "3.4.1"
tokio-util = "0.7.9"
serde = "1.0.188"
serde_json = "1.0.107"
# sentry = { version = "0.27.0", optional = true }
# sentry-tracing = { version = "0.27.0", optional = true }
async-tungstenite = { version = "0.23.0", features = ["tokio-runtime"] }
thiserror = "1.0.48"
getset = "0.1.2"
async-trait = "0.1.73"
once_cell = "1.18.0"
lazy_static = "1.4.0"
console-subscriber = { version="0.1.10", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
vergen = "7.5.1"
anyhow = "1.0.71"

[patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
# sentry = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
# sentry-tracing = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
