[package]
name = "intiface-cli"
version = "6.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Command Line Interface frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-cli-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"

[dependencies]
buttplug = { path = "../buttplug-rs/buttplug", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
# buttplug = { version = "0.6.0", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
argh = "0.1.3"
async-std = { version = "1.6.3", features = ["attributes"] }
rcgen = "0.8.5"
log = "0.4.11"
futures = "0.3.5"
prost = "0.6.1"
async-channel = "1.4.1"
tracing-fmt = "0.1.1"
tracing-subscriber = "0.2.11"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.9"

[build-dependencies]
prost-build = "0.6.1"
vergen = "3.1.0"
