[package]
name = "intiface-engine"
version = "1.4.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "CLI and Library frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-engine.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2021"
exclude = [".vscode/**"]

[lib]
name = "intiface_engine"
path = "src/lib.rs"

[[bin]]
name = "intiface-engine"
path = "src/bin/main.rs"

[features]
default=["crash_reporting"]
# crash_reporting=["sentry", "sentry-tracing"]
# Make crash reporting a null feature for now.
crash_reporting=[]
tokio_console=["console-subscriber"]

[dependencies]
# buttplug = { path = "../buttplug/buttplug" }
buttplug = { version = "7.1.0" }
argh = "0.1.10"
log = "0.4.17"
futures = "0.3.28"
tracing-fmt = "0.1.1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing = "0.1.37"
tokio = { version = "1.28.1", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
backtrace = "0.3.67"
ctrlc = "3.3.0"
tokio-util = "0.7.8"
serde = "1.0.163"
serde_json = "1.0.96"
# sentry = { version = "0.27.0", optional = true }
# sentry-tracing = { version = "0.27.0", optional = true }
async-tungstenite = { version = "0.22.2", features = ["tokio-runtime"] }
thiserror = "1.0.40"
getset = "0.1.2"
async-trait = "0.1.68"
once_cell = "1.17.1"
lazy_static = "1.4.0"
console-subscriber = { version="0.1.9", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
vergen = "7.5.0"
anyhow = "1.0.71"

[patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
# sentry = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
# sentry-tracing = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
