[package]
name = "intiface-engine"
version = "1.0.3"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "CLI and Library frontend for the Buttplug sex toy control library"
license = "BSD-3-Clause"
homepage = "http://intiface.com"
repository = "https://github.com/intiface/intiface-engine.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2021"
exclude = [".vscode/**"]

[lib]
name = "intiface_engine"
path = "src/lib.rs"

[[bin]]
name = "intiface-engine"
path = "src/bin/main.rs"

[features]
default=["crash_reporting", "desktop"]
tokio_console=["console-subscriber"]
desktop=["buttplug/xinput-manager", "buttplug/serial-manager", "buttplug/lovense-dongle-manager", "buttplug/lovense-connect-service-manager",]

[dependencies]
# buttplug = { path = "../buttplug-rs/buttplug", default_features = false, features = ["tokio-runtime", "client", "server", "serialize-json", "websockets", "btleplug-manager", "websocket-server-manager"] }
buttplug = { version = "6.2.1", default_features = false, features = ["tokio-runtime", "client", "server", "serialize-json", "websockets", "btleplug-manager", "websocket-server-manager"] }
argh = "0.1.9"
log = "0.4.17"
futures = "0.3.25"
tracing-fmt = "0.1.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
tracing = "0.1.37"
tokio = { version = "1.22.0", features = ["sync", "rt-multi-thread", "macros", "io-std", "fs", "signal", "io-util"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
backtrace = "0.3.66"
ctrlc = "3.2.3"
tokio-util = "0.7.4"
serde = "1.0.147"
serde_json = "1.0.89"
sentry = { version = "0.27.0", optional = true }
sentry-tracing = { version = "0.27.0", optional = true }
async-tungstenite = { version = "0.18.0", features = ["tokio-runtime"] }
thiserror = "1.0.37"
getset = "0.1.2"
async-trait = "0.1.58"
once_cell = "1.16.0"
lazy_static = "1.4.0"
console-subscriber = { version="0.1.8", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[build-dependencies]
vergen = "7.4.2"
anyhow = "1.0.66"

[patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
sentry = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
sentry-tracing = { git = "https://github.com/getsentry/sentry-rust", branch = "master" }
